# Generated by Django 2.0.2 on 2018-03-02 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Otp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret', models.CharField(max_length=50, verbose_name='secret')),
                ('name', models.CharField(help_text='Account Name for Provisioning URI, to be used when need URI for QR code.', max_length=50, verbose_name='account name')),
                ('issuer_name', models.CharField(help_text='Issuer Name for Provisioning URI.', max_length=50, verbose_name='issuer name')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='otp', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'otp',
                'verbose_name_plural': 'otp',
            },
        ),
        migrations.CreateModel(
            name='RecoveryCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=12, unique=True, verbose_name='code')),
                ('is_enable', models.BooleanField(default=True, verbose_name='enable')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_codes', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'recovery code',
                'verbose_name_plural': 'recovery codes',
            },
        ),
    ]
